name: final_year_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
#---------------------------------PACKAGES---------------------#
dependencies:
  flutter:
    sdk: flutter


 # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_stripe: ^11.1.0
  dio: ^5.7.0
  crypto: ^3.0.0

  # Icons
  font_awesome_flutter: any
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.2.0
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.3.0



#------------------- PACKAGES END -----------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/user/
    - assets/icons/payment_methods/



  fonts:
     - family: Kanit
       fonts:
         - asset: assets/fonts/Kanit-Light.ttf
           weight: 300
         - asset: assets/fonts/Kanit-Regular.ttf
           weight: 400
         - asset: assets/fonts/Kanit-Italic.ttf
           style: italic
         - asset: assets/fonts/Kanit-Medium.ttf
           weight: 500
         - asset: assets/fonts/Kanit-MediumItalic.ttf
           weight: 500
         - asset: assets/fonts/Kanit-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Kanit-Bold.ttf
           weight: 800

