// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp380ACaZQuOY83Jbi0UGyfnFpPxEY6CA',
    appId: '1:190321359551:android:3c7dad38417176c459e40a',
    messagingSenderId: '190321359551',
    projectId: 'final-year-project-b2150',
    storageBucket: 'final-year-project-b2150.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLy3vLR439GzHneC2D2BZWc7gCGrTj4zo',
    appId: '1:190321359551:ios:c2ae7a2cbc590e8559e40a',
    messagingSenderId: '190321359551',
    projectId: 'final-year-project-b2150',
    storageBucket: 'final-year-project-b2150.appspot.com',
    androidClientId: '190321359551-u2q8h8gdhgnn5jlbtj5ccqr8nc1dcucc.apps.googleusercontent.com',
    iosClientId: '190321359551-jd2bgag23pdrog77103gentcgkss4gpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );
}
